### ISSUE TITLE
How to receive weight data after value received and handshake success?

### ISSUE THREAD

**Issue by hynra** [elinkthings/AiLinkSecretFlutter#2]
I'm able to connect to AiLink smart-scale device following this instruction and the example code provided in the repo:

![image](https://github.com/user-attachments/assets/c3fc2d78-5802-4e5d-bb1a-8dad53b5ffaa)

The question is after two values are received successfully, and two replies handshake are performed, how to get weight data? Because I am stuck in this process:

![WhatsApp Image 2024-07-26 at 17 35 04 (2)](https://github.com/user-attachments/assets/aec1e10c-d07e-4f2d-9a39-bf2ace25adf8).

Also, it stops at the second value received, even if the scale device has received weight and still counting, the app never receives value anymore. Please help.

Here is the full code:

```dart
import 'dart:async';
import 'dart:typed_data';

import 'package:ailink/ailink.dart';
import 'package:ailink/utils/ble_common_util.dart';
import 'package:ailink/utils/common_extensions.dart';
import 'package:ailink/utils/elink_cmd_utils.dart';
import 'package:app/component/widget_ble_state.dart';
import 'package:app/component/widget_operate_btn.dart';
import 'package:app/impl/elink_common_data_parse_callback.dart';
import 'package:app/utils/elink_common_cmd_utils.dart';
import 'package:app/utils/elink_common_data_parse_utils.dart';
import 'package:app/utils/extensions.dart';
import 'package:app/utils/log_utils.dart';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_blue_plus/flutter_blue_plus.dart';

class ConnectDevicePage extends StatefulWidget {
  const ConnectDevicePage({super.key, required this.device});

  final BluetoothDevice device;

  @override
  State<ConnectDevicePage> createState() => _ConnectDevicePageState();
}

class _ConnectDevicePageState extends State<ConnectDevicePage> {
  final logList = <String>[];

  final _ailinkPlugin = Ailink();
  final ScrollController _controller = ScrollController();

  BluetoothDevice? _bluetoothDevice;
  StreamSubscription<BluetoothConnectionState>? _connectionStateSubscription;
  StreamSubscription<List<int>>? _onReceiveDataSubscription;

  BluetoothCharacteristic? _dataA6Characteristic;
  late ElinkCommonDataParseUtils _elinkCommonDataParseUtils;

  @override
  void initState() {
    super.initState();
    _addLog('initState');
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _addLog('addPostFrameCallback');
      _bluetoothDevice = widget.device;
      _connectionStateSubscription =
          _bluetoothDevice?.connectionState.listen((state) {
        if (state.isConnected) {
          _addLog('Connected');
          _bluetoothDevice?.discoverServices().then((services) {
            _addLog(
                'DiscoverServices success: ${services.map((e) => e.serviceUuid).join(',').toUpperCase()}');
            if (services.isNotEmpty) {
              _setNotify(services);
            }
          }, onError: (error) {
            _addLog('DiscoverServices error');
          });
        } else {
          _dataA6Characteristic = null;
          _addLog(
              'Disconnected: code(${_bluetoothDevice?.disconnectReason?.code}), desc(${_bluetoothDevice?.disconnectReason?.description})');
        }
      });
      _bluetoothDevice?.connect();
    });

    _elinkCommonDataParseUtils = ElinkCommonDataParseUtils();
    _elinkCommonDataParseUtils.setElinkCommonDataParseCallback(
        ElinkCommonDataParseCallback((version) {
      _addLog('onGetBmVersion: $version');
    }));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              _bluetoothDevice?.advName ?? 'Unknown',
              style: const TextStyle(fontSize: 18),
            ),
            StreamBuilder<BluetoothConnectionState>(
              initialData: BluetoothConnectionState.disconnected,
              stream: _bluetoothDevice?.connectionState,
              builder: (context, snapshot) {
                final state =
                    snapshot.data ?? BluetoothConnectionState.disconnected;
                return Text(
                  state.isConnected ? 'Connected' : 'Disconnected',
                  style: const TextStyle(fontSize: 14),
                );
              },
            )
          ],
        ),
        leading: IconButton(
          onPressed: () => Navigator.pop(context),
          icon: const Icon(
            Icons.arrow_back,
          ),
        ),
        actions: [
          BleStateWidget(
            bluetoothDevice: _bluetoothDevice,
            onPressed: () {
              _bluetoothDevice?.connect();
            },
          ),
        ],
      ),
      body: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              OperateBtnWidget(
                onPressed: () async {
                  if (_dataA6Characteristic != null) {
                    _restartBleModule(_dataA6Characteristic!);
                  }
                },
                title: 'RestartBle',
              ),
              OperateBtnWidget(
                onPressed: () async {
                  if (_dataA6Characteristic != null) {
                    _getBmVersion(_dataA6Characteristic!);
                  }
                },
                title: 'GetBmVersion',
              ),
            ],
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              OperateBtnWidget(
                onPressed: () async {
                  if (_dataA6Characteristic != null) {
                    _setHandShake(_dataA6Characteristic!);
                  }
                },
                title: 'SetHandShake',
              ),
              OperateBtnWidget(
                onPressed: () async {
                  if (_dataA6Characteristic != null) {
                    _clearHandShake(_dataA6Characteristic!);
                  }
                },
                title: 'ClearHandShake',
              ),
            ],
          ),
          Expanded(
            child: ListView.separated(
              controller: _controller,
              itemBuilder: (context, index) {
                return Padding(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 12.0, vertical: 8.0),
                  child: Text(
                    '${DateTime.now()}: \n${logList[index]}',
                    style: TextStyle(
                      color: index % 2 == 0 ? Colors.black : Colors.black87,
                      fontSize: 16,
                    ),
                  ),
                );
              },
              separatorBuilder: (context, index) {
                return const Divider(
                  height: 0.5,
                  color: Colors.grey,
                );
              },
              itemCount: logList.length,
            ),
          ),
        ],
      ),
    );
  }

  void _setNotify(List<BluetoothService> services) async {
    final service = services.firstWhere((service) => service.serviceUuid.str
        .equal(ElinkBleCommonUtils.elinkConnectDeviceUuid));
    _addLog(
        '_setNotify characteristics: ${service.characteristics.map((e) => e.uuid).join(',').toUpperCase()}');
    for (var characteristic in service.characteristics) {
      if (characteristic.uuid.str.equal(ElinkBleCommonUtils.elinkNotifyUuid) ||
          characteristic.uuid.str
              .equal(ElinkBleCommonUtils.elinkWriteAndNotifyUuid)) {
        _addLog('_setNotify characteristics uuid: ${characteristic.uuid}');
        await characteristic.setNotifyValue(true);
        if (characteristic.uuid.str
            .equal(ElinkBleCommonUtils.elinkWriteAndNotifyUuid)) {
          _onReceiveDataSubscription =
              characteristic.onValueReceived.listen((data) {
            _addLog(
                'OnValueReceived [${characteristic.uuid.str}]: ${data.toHex()}, checked: ${ElinkCmdUtils.checkElinkCmdSum(data)}');
            if (ElinkBleCommonUtils.isSetHandShakeCmd(data)) {
              _replyHandShake(characteristic, data); //
            }
            if (ElinkBleCommonUtils.isGetHandShakeCmd(data)) {
              Future.delayed(const Duration(milliseconds: 500), () async {
                final handShakeStatus = await _ailinkPlugin
                    .checkHandShakeStatus(Uint8List.fromList(data));
                _addLog('handShakeStatus: $handShakeStatus');
              });
            }
            _elinkCommonDataParseUtils.parseElinkCommonData(data);
          });

          _dataA6Characteristic = characteristic;
          // await _restartBleModule(characteristic);
          LogUtils().log("characteristic: $characteristic");
            _setHandShake(characteristic);
        }
      }
    }
  }

  Future<void> _setHandShake(BluetoothCharacteristic characteristic) async {
    Uint8List data = (await _ailinkPlugin.initHandShake()) ?? Uint8List(0);
    _addLog('_setHandShake: ${data.toHex()}');
    await characteristic.write(data.toList(), withoutResponse: true);
  }

  Future<void> _clearHandShake(BluetoothCharacteristic characteristic) async {

    final data = ElinkCommonCmdUtils.clearElinkHandShake();
    _addLog('_clearHandShake: ${data.toHex()}');
    await characteristic.write(data, withoutResponse: true);
  }

  Future<void> _restartBleModule(BluetoothCharacteristic characteristic) async {
    final data = ElinkCommonCmdUtils.restartElinkBleModule();
    _addLog('_restartBleModule: ${data.toHex()}');
    await characteristic.write(data, withoutResponse: true);
  }

  Future<void> _getBmVersion(BluetoothCharacteristic characteristic) async {
    final data = ElinkCommonCmdUtils.getElinkBmVersion();
    _addLog('_getBmVersion: ${data.toHex()}');
    await characteristic.write(data, withoutResponse: true);
  }

  Future<void> _replyHandShake(
      BluetoothCharacteristic characteristic, List<int> data) async {
    Uint8List replyData = (await _ailinkPlugin
            .getHandShakeEncryptData(Uint8List.fromList(data))) ??
        Uint8List(0);
    _addLog('_replyHandShake: ${replyData.toHex()}');
    await characteristic.write(replyData.toList(), withoutResponse: true);
  }

  void _addLog(String log) {
    if (mounted) {
      setState(() {
        logList.insert(0, log);
      });
    }
  }

  void _scrollToBottom() {
    _controller.animateTo(
      _controller.position.maxScrollExtent,
      duration: const Duration(milliseconds: 500),
      curve: Curves.easeInOut,
    );
  }

  @override
  void dispose() {
    _bluetoothDevice?.disconnect();
    _bluetoothDevice = null;
    _dataA6Characteristic = null;
    _onReceiveDataSubscription?.cancel();
    _connectionStateSubscription?.cancel();
    _controller.dispose();
    super.dispose();
  }
}

```

**Comment by flutter-vrinsoft** [comment]
Same thing we are facing from last one week. we are using Kitchen Scaler. Implemented code as per given instruction but not able to get data from it. @elinkthings please assist ahed with proper example and video.

**Comment by hynra** [comment]
> Same thing we are facing from last one week. we are using Kitchen Scaler. Implemented code as per given instruction but not able to get data from it. @elinkthings please assist ahed with proper example and video.

I even tried using native Android SDK, and the result was the same.

**Comment by hynra** [comment]
It seems like I can receive value stream, here the updated lines:

```dart
 ...
        } else if (characteristic.uuid.str
            .equal(ElinkBleCommonUtils.elinkNotifyUuid)) {
          _onReceiveWeightDataSubscription = characteristic.onValueReceived.listen((data) {
            _processReceivedData(data);
          });
...

  Future<void> _processReceivedData(List<int> data) async {
    try {
      final decryptedData = await _ailinkPlugin.decryptBroadcast(Uint8List.fromList(data));
      if (decryptedData != null) {
        final weightData = BroadcastScaleDataUtils().getWeightData(decryptedData);
        if (weightData != null) {
          setState(() {
            _currentWeight = "${weightData.weightStr} ${weightData.weightUnitStr}";
          });
          _addLog('Weight: $_currentWeight');

...
```

but the data I received was always the same. Does `BroadcastScaleDataUtils().getWeightData` only work for broadcast devices?

**Comment by elinkthings** [comment]
> It seems like I can receive value stream, here the updated lines:
> 
> ```dart
>  ...
>         } else if (characteristic.uuid.str
>             .equal(ElinkBleCommonUtils.elinkNotifyUuid)) {
>           _onReceiveWeightDataSubscription = characteristic.onValueReceived.listen((data) {
>             _processReceivedData(data);
>           });
> ...
> 
>   Future<void> _processReceivedData(List<int> data) async {
>     try {
>       final decryptedData = await _ailinkPlugin.decryptBroadcast(Uint8List.fromList(data));
>       if (decryptedData != null) {
>         final weightData = BroadcastScaleDataUtils().getWeightData(decryptedData);
>         if (weightData != null) {
>           setState(() {
>             _currentWeight = "${weightData.weightStr} ${weightData.weightUnitStr}";
>           });
>           _addLog('Weight: $_currentWeight');
> 
> ...
> ```
> 
> but the data I received was always the same. Does `BroadcastScaleDataUtils().getWeightData` only work for broadcast devices?

The ailink library currently provides the following functionalities: processing broadcast data (retrieving MAC, CID, VID, PID), processing broadcast scale data, handling elink's general A6 and A7 protocol command data, processing handshake protocol commands, and processing firmware version data.

To integrate various devices, you will need to handle the protocols based on the documentation provided by our company.

**Comment by hynra** [comment]
> > It seems like I can receive value stream, here the updated lines:
> > ```dart
> >  ...
> >         } else if (characteristic.uuid.str
> >             .equal(ElinkBleCommonUtils.elinkNotifyUuid)) {
> >           _onReceiveWeightDataSubscription = characteristic.onValueReceived.listen((data) {
> >             _processReceivedData(data);
> >           });
> > ...
> > 
> >   Future<void> _processReceivedData(List<int> data) async {
> >     try {
> >       final decryptedData = await _ailinkPlugin.decryptBroadcast(Uint8List.fromList(data));
> >       if (decryptedData != null) {
> >         final weightData = BroadcastScaleDataUtils().getWeightData(decryptedData);
> >         if (weightData != null) {
> >           setState(() {
> >             _currentWeight = "${weightData.weightStr} ${weightData.weightUnitStr}";
> >           });
> >           _addLog('Weight: $_currentWeight');
> > 
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but the data I received was always the same. Does `BroadcastScaleDataUtils().getWeightData` only work for broadcast devices?
> 
> The ailink library currently provides the following functionalities: processing broadcast data (retrieving MAC, CID, VID, PID), processing broadcast scale data, handling elink's general A6 and A7 protocol command data, processing handshake protocol commands, and processing firmware version data.
> 
> To integrate various devices, you will need to handle the protocols based on the documentation provided by our company.

Where can I find the documentation ?

**Comment by elinkthings** [comment]
> > > It seems like I can receive value stream, here the updated lines:
> > > ```dart
> > >  ...
> > >         } else if (characteristic.uuid.str
> > >             .equal(ElinkBleCommonUtils.elinkNotifyUuid)) {
> > >           _onReceiveWeightDataSubscription = characteristic.onValueReceived.listen((data) {
> > >             _processReceivedData(data);
> > >           });
> > > ...
> > > 
> > >   Future<void> _processReceivedData(List<int> data) async {
> > >     try {
> > >       final decryptedData = await _ailinkPlugin.decryptBroadcast(Uint8List.fromList(data));
> > >       if (decryptedData != null) {
> > >         final weightData = BroadcastScaleDataUtils().getWeightData(decryptedData);
> > >         if (weightData != null) {
> > >           setState(() {
> > >             _currentWeight = "${weightData.weightStr} ${weightData.weightUnitStr}";
> > >           });
> > >           _addLog('Weight: $_currentWeight');
> > > 
> > > ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > but the data I received was always the same. Does `BroadcastScaleDataUtils().getWeightData` only work for broadcast devices?
> > 
> > 
> > The ailink library currently provides the following functionalities: processing broadcast data (retrieving MAC, CID, VID, PID), processing broadcast scale data, handling elink's general A6 and A7 protocol command data, processing handshake protocol commands, and processing firmware version data.
> > To integrate various devices, you will need to handle the protocols based on the documentation provided by our company.
> 
> Where can I find the documentation ?

You can contact the corresponding business colleague in our company and ask which company you are from?

**Comment by hynra** [comment]
> > > > It seems like I can receive value stream, here the updated lines:
> > > > ```dart
> > > >  ...
> > > >         } else if (characteristic.uuid.str
> > > >             .equal(ElinkBleCommonUtils.elinkNotifyUuid)) {
> > > >           _onReceiveWeightDataSubscription = characteristic.onValueReceived.listen((data) {
> > > >             _processReceivedData(data);
> > > >           });
> > > > ...
> > > > 
> > > >   Future<void> _processReceivedData(List<int> data) async {
> > > >     try {
> > > >       final decryptedData = await _ailinkPlugin.decryptBroadcast(Uint8List.fromList(data));
> > > >       if (decryptedData != null) {
> > > >         final weightData = BroadcastScaleDataUtils().getWeightData(decryptedData);
> > > >         if (weightData != null) {
> > > >           setState(() {
> > > >             _currentWeight = "${weightData.weightStr} ${weightData.weightUnitStr}";
> > > >           });
> > > >           _addLog('Weight: $_currentWeight');
> > > > 
> > > > ...
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > but the data I received was always the same. Does `BroadcastScaleDataUtils().getWeightData` only work for broadcast devices?
> > > 
> > > 
> > > The ailink library currently provides the following functionalities: processing broadcast data (retrieving MAC, CID, VID, PID), processing broadcast scale data, handling elink's general A6 and A7 protocol command data, processing handshake protocol commands, and processing firmware version data.
> > > To integrate various devices, you will need to handle the protocols based on the documentation provided by our company.
> > 
> > 
> > Where can I find the documentation ?
> 
> You can contact the corresponding business colleague in our company and ask which company you are from?

So it's closed sdk? We bought several baby weight scale & adult weight scale. We plan to integrate with our custom app for particular features.

**Comment by elinkthings** [comment]
> So it's closed sdk? We bought several baby weight scale & adult weight scale. We plan to integrate with our custom app for particular features.

Flutter does not currently provide a weight scale, you can use the Android and iOS SDKs

**Comment by elinkthings** [comment]
> > > > > It seems like I can receive value stream, here the updated lines:
> > > > > ```
> > > > >  ...
> > > > >         } else if (characteristic.uuid.str
> > > > >             .equal(ElinkBleCommonUtils.elinkNotifyUuid)) {
> > > > >           _onReceiveWeightDataSubscription = characteristic.onValueReceived.listen((data) {
> > > > >             _processReceivedData(data);
> > > > >           });
> > > > > ...
> > > > > 
> > > > >   Future<void> _processReceivedData(List<int> data) async {
> > > > >     try {
> > > > >       final decryptedData = await _ailinkPlugin.decryptBroadcast(Uint8List.fromList(data));
> > > > >       if (decryptedData != null) {
> > > > >         final weightData = BroadcastScaleDataUtils().getWeightData(decryptedData);
> > > > >         if (weightData != null) {
> > > > >           setState(() {
> > > > >             _currentWeight = "${weightData.weightStr} ${weightData.weightUnitStr}";
> > > > >           });
> > > > >           _addLog('Weight: $_currentWeight');
> > > > > 
> > > > > ...
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > but the data I received was always the same. Does `BroadcastScaleDataUtils().getWeightData` only work for broadcast devices?
> > > > 
> > > > 
> > > > The ailink library currently provides the following functionalities: processing broadcast data (retrieving MAC, CID, VID, PID), processing broadcast scale data, handling elink's general A6 and A7 protocol command data, processing handshake protocol commands, and processing firmware version data.
> > > > To integrate various devices, you will need to handle the protocols based on the documentation provided by our company.
> > > 
> > > 
> > > Where can I find the documentation ?
> > 
> > 
> > You can contact the corresponding business colleague in our company and ask which company you are from?
> 
> So it's closed sdk? We bought several baby weight scale & adult weight scale. We plan to integrate with our custom app for particular features.

Flutter does not currently provide a weight scale, you can use the Android and iOS SDKs

**Comment by hynra** [comment]
Ok, I've manually implemented weight scale devices (non-broadcast).
First, do a handshake with this format (found on doc spec):
```dart
    final List<int> handshakeData = [
      0xA6,
      0x03,
      0x42,
      0x01,
      0x00,
      0x46,
      0x6A
    ];

    _addLog("_setHandShake without encryption ${handshakeData .toHex()}");
    await characteristic.write(handshakeData .toList(), withoutResponse: true);
```

now, listen to data transmitted by the device via FFE2

```dart
if (characteristic.uuid.str.equal(ElinkBleCommonUtils.elinkNotifyUuid)) {
     _onReceiveWeightDataSubscription = characteristic.onValueReceived.listen((data) async {
         _processReceivedData(data);
     });
  }
```

process the A7 data:
```dart
  Future<void> _processReceivedData(List<int> data) async {
    LogUtils().log("Received data: ${data.map((e) => e.toRadixString(16).padLeft(2, '0')).join(' ')}");

    WeightScaleData? weightData = parseWeightData(data);
    if (weightData != null) {
      setState(() {
        _lastWeightData = weightData;
        _currentWeight = "${weightData.isNegative ? "-" : ""}${weightData.weight.toStringAsFixed(2)} ${weightData.unit}";
      });
      _addLog("Parsed weight: $weightData");
    } else {
      _addLog("Failed to parse weight data");
    }
  }
```

Here's how to read A7 data into a readable format:
```dart

class WeightScaleData{
  final bool isStable;
  final double weight;
  final String unit;
  final bool isNegative;

  WeightScaleData({
    required this.isStable,
    required this.weight,
    required this.unit,
    required this.isNegative,
  });

  @override
  String toString() {
    return 'WeightData(isStable: $isStable, weight: ${isNegative ? "-" : ""}$weight $unit)';
  }
}

WeightScaleData? parseWeightData(List<int> data) {
  if (data.length != 11 || data[0] != 0xA7 || data[10] != 0x7A) {
    print("Invalid data format");
    return null;
  }

  bool isStable = data[4] == 0x01;
  int rawWeight = (data[5] << 8) | data[6];
  String unit;
  switch (data[7]) {
    case 0x00: unit = 'kg'; break;
    case 0x01: unit = 'jin'; break;
    case 0x02: unit = 'lb:oz'; break;
    case 0x03: unit = 'oz'; break;
    case 0x04: unit = 'st:lb'; break;
    case 0x05: unit = 'g'; break;
    case 0x06: unit = 'lb'; break;
    default: unit = 'unknown';
  }
  bool isNegative = (data[8] & 0x10) != 0;
  int decimalPoints = data[8] & 0x0F;

  double weight = rawWeight / pow(10, decimalPoints);

  return WeightScaleData(
    isStable: isStable,
    weight: weight,
    unit: unit,
    isNegative: isNegative,
  );
}
```

Also, if you want to force the unit into KG, you can do this after handshake:

```dart
  Future<void> _setDeviceUnitToKG(
      BluetoothCharacteristic characteristic) async {
    final List<int> setUnitData = [
      0xA7,
      0x00,
      0x04,
      0x81,
      0x00,
      0x00,
      0x85,
      0x7A
    ];

    _addLog("Sent set unit to KG instruction");
    await characteristic.write(setUnitData.toList(), withoutResponse: true);
  }
```

I hope it helps anyone looking for the same solution.
